Repository shi-institute/gc-mobility-dashboard, pull requests merged in 2025-08, with the labels that each got.

#66 feat(pipeline/census_acs_5year): add `areas` property to `time_series.json` with the area names that correspond to the associated tract
  data-pipeline/src/etl/sources/census_acs_5year/constants.py
  data-pipeline/src/etl/sources/census_acs_5year/runner.py
  data-pipeline/src/etl/sources/census_acs_5year/tract_etl.py
Labels: enhancement

#67 feat(pipeline/replica): add handling/optimizations for large areas that far exceed reasonable amounts of memory utilization
  data-pipeline/environment.yaml
  data-pipeline/src/TeeLogger.py
  data-pipeline/src/etl/sources/replica/etl.py
  data-pipeline/src/etl/sources/replica/process_etl.py
  data-pipeline/src/etl/sources/replica/readers/partitions_to_gdf.py
  data-pipeline/src/etl/sources/replica/transformers/as_points.py
  data-pipeline/src/etl/sources/replica/transformers/count_segment_frequency.py
  data-pipeline/src/etl/sources/replica/transformers/to_vector_tiles.py
  data-pipeline/src/etl/sources/replica/transformers/trips_as_lines.py
  data-pipeline/src/main.py
Labels: bug, enhancement

#68 feat: add service coverge statistics
  data-pipeline/src/etl/geodesic.py
  data-pipeline/src/etl/sources/greenlink_gtfs/etl.py
  data-pipeline/src/etl/sources/greenlink_gtfs/runner.py
  data-pipeline/src/etl/sources/replica/process_etl.py
  frontend/src/data.d.ts
  frontend/src/hooks/useAppData.ts
  frontend/src/utils/generateHash.ts
  frontend/src/utils/index.ts
  frontend/src/views/GeneralAccess.tsx
Labels: enhancement

#69 feat(frontend): show boardings and alightings service statistics
  frontend/src/hooks/useAppData.ts
  frontend/src/views/GeneralAccess.tsx
Labels: enhancement

#70 feat: calculate stop count and show it on the frontend
  data-pipeline/src/etl/sources/greenlink_gtfs/etl.py
  frontend/src/data.d.ts
  frontend/src/views/GeneralAccess.tsx
Labels: enhancement

#62 feat: add TreeMap component with responsive layouts for job access data
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/Section/Section.tsx
  frontend/src/components/common/TreeMap/TreeMap.tsx
  frontend/src/components/common/index.ts
  frontend/src/components/layout/CoreFrame/CoreFrame.tsx
  frontend/src/utils/hasKey.ts
  frontend/src/utils/index.ts
  frontend/src/views/JobAccess.tsx
Labels: enhancement

#74 feat(pipeline): dissolve walksheds and bikesheds
  data-pipeline/src/etl/sources/greenlink_gtfs/etl.py
Labels: enhancement

#76 feat: add essential services data
  .github/workflows/data-pipeline-test.yaml
  data-pipeline/src/etl/geodesic.py
  data-pipeline/src/etl/sources/essential_services/etl.py
  data-pipeline/src/etl/sources/essential_services/runner.py
  data-pipeline/src/etl/sources/geocoder/etl.py
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/common/Select/SelectOne.tsx
  frontend/src/components/options/areas/SelectedArea.tsx
  frontend/src/components/options/seasons/SelectedSeason.tsx
  frontend/src/data.d.ts
  frontend/src/hooks/useAppData.ts
  frontend/src/hooks/useMapData.tsx
  frontend/src/views/EssentialServicesAccess.tsx
  frontend/src/views/GeneralAccess.tsx
  frontend/src/views/RoadsVsTransit.tsx
  frontend/tsconfig.app.json
Labels: enhancement

#82 feat: show remaining census data on tab 1 (general access)
  data-pipeline/src/etl/sources/census_acs_5year/tract_etl.py
  frontend/src/data.d.ts
  frontend/src/hooks/useAppData.ts
  frontend/src/views/GeneralAccess.tsx
Labels: bug, enhancement

#84 feat(pipeline): add ETL for passthrough data files and folders
  data-pipeline/src/etl/sources/passthrough/runner.py
Labels: enhancement

#85 feat(frontend): show future scenarios and routes on tab 5 (roads or transit)
  frontend/beforeStart.js
  frontend/src/assets/theme.css
  frontend/src/components/common/IconButton/IconButton.tsx
  frontend/src/components/common/Map/Map.tsx
  frontend/src/components/layout/OptionTrack/OptionButton.tsx
  frontend/src/components/layout/OptionTrack/OptionTrack.tsx
  frontend/src/data.d.ts
  frontend/src/hooks/useAppData.ts
  frontend/src/hooks/useMapData.tsx
  frontend/src/utils/renderers/createBusStopRenderer.ts
  frontend/src/views/RoadsVsTransit.tsx
Labels: enhancement

#86 feat: add map, coverage stats, work and school stats, and travel mode figure for tab 2 (future opportunities)
  data-pipeline/src/etl/sources/future_routes/etl.py
  frontend/src/components/common/Statistic/plot/presets/hoizontalBar.ts
  frontend/src/components/options/futures/SelectedFutureRoutes.tsx
  frontend/src/components/options/futures/index.ts
  frontend/src/components/options/index.ts
  frontend/src/data.d.ts
  frontend/src/hooks/useAppData.ts
  frontend/src/hooks/useMapData.tsx
  frontend/src/views/FutureOpportunities.tsx
  frontend/src/views/GeneralAccess.tsx
Labels: enhancement

#89 feat(frontend): show local funding per capita on tab 1 (general access)
  frontend/src/components/common/Statistic/Money.tsx
  frontend/src/components/common/Statistic/StatisticContainer.ts
  frontend/src/components/common/Statistic/index.ts
  frontend/src/data.d.ts
  frontend/src/hooks/useAppData.ts
  frontend/src/views/GeneralAccess.tsx
Labels: enhancement

#92 feat: split healthcare access data into dental, eye, family medicine, free clinic, hospital, internal medicine, and urgent care
  data-pipeline/src/etl/sources/essential_services/etl.py
  frontend/src/data.d.ts
  frontend/src/hooks/useAppData.ts
  frontend/src/hooks/useMapData.tsx
  frontend/src/views/EssentialServicesAccess.tsx
Labels: enhancement

#93 feat(pipeline/replica): disable saturday trip processing
  data-pipeline/src/etl/sources/replica/etl.py
Labels: enhancement

#94 fix(frontend): insert pathname in front of VectorTileServer url relative paths - support for loading from a subfolder url instead of the root of the domain/subdomain
  frontend/src/hooks/useAppData.ts
Labels: bug

#97 fix(frontend): show section names on tabs in mobile view
  frontend/src/components/layout/CoreFrame/CoreFrame.tsx
Labels: enhancement

#100 feat(frontend): show count of new routes
  frontend/src/views/RoadsVsTransit.tsx
Labels: enhancement

#102 fix(pipeline): use correct replica etl name as dependency for future_routes
  data-pipeline/src/etl/sources/future_routes/runner.py
Labels: bug

#116 feat(frontend): zoom to selected areas on tabs 1, 2, and 4
  frontend/src/components/common/Map/Map.tsx
  frontend/src/hooks/useMapData.tsx
  frontend/src/views/EssentialServicesAccess.tsx
  frontend/src/views/FutureOpportunities.tsx
  frontend/src/views/GeneralAccess.tsx
Labels: enhancement

#118 feat: support specifying a different data origin and pathname via the GCMD_DATA_ORIGIN and GCMD_DATA_PATH environment variables
  frontend/package.json
  frontend/src/hooks/useAppData.ts
  frontend/src/vite-env.d.ts
  frontend/vite.config.ts
Labels: enhancement

#123 feat: count bus stop ids instead of using the count property
  frontend/src/data.d.ts
  frontend/src/hooks/useAppData.ts
  frontend/src/views/RoadsVsTransit.tsx
Labels: enhancement

#135 feat(frontend): add headers to the top of tabs 1, 2, and 4
  frontend/src/assets/theme.css
  frontend/src/components/layout/PageHeader/PageHeader.tsx
  frontend/src/components/layout/index.ts
  frontend/src/utils/index.ts
  frontend/src/utils/listOxford.ts
  frontend/src/utils/replaceLast.ts
  frontend/src/views/EssentialServicesAccess.tsx
  frontend/src/views/FutureOpportunities.tsx
  frontend/src/views/GeneralAccess.tsx
  frontend/src/views/JobAccess.tsx
Labels: enhancement

#141 feat(frontend): automatically select the first area and last season when none are currently selected
  frontend/src/hooks/useAppData.ts
  frontend/src/views/GeneralAccess.tsx
  frontend/src/views/JobAccess.tsx
Labels: enhancement

#143 feat(frontend): show simplified options for areas and seasons at the top of tab sections (tabs 1, 2 and 4)
  frontend/src/components/layout/CoreFrame/CoreFrame.tsx
  frontend/src/components/layout/CoreFrame/CoreFrameContext.ts
  frontend/src/components/layout/PageHeader/PageHeader.tsx
  frontend/src/views/EssentialServicesAccess.tsx
  frontend/src/views/FutureOpportunities.tsx
  frontend/src/views/GeneralAccess.tsx
Labels: enhancement

#144 feat(frontend): show loading indicators and overlay when data is downloading
  frontend/src/components/common/ProgressRing/ProgressRing.tsx
  frontend/src/components/common/index.ts
  frontend/src/components/layout/CoreFrame/CoreFrame.tsx
  frontend/src/hooks/useAppData.ts
  frontend/src/views/EssentialServicesAccess.tsx
  frontend/src/views/FutureOpportunities.tsx
  frontend/src/views/GeneralAccess.tsx
  frontend/src/views/JobAccess.tsx
  frontend/src/views/RoadsVsTransit.tsx
Labels: enhancement

#146 feat(frontend): implement Vanessa's paratransit and walkshed icons
  frontend/src/components/common/IconButton/ParatransitIcon.tsx
  frontend/src/components/common/IconButton/WalkshedIcon.tsx
  frontend/src/components/common/Map/Map.tsx
Labels: enhancement

#149 feat(frontend): consolidate future route layer labels in the legend
  frontend/src/components/common/Map/Map.tsx
  frontend/src/hooks/useMapData.tsx
Labels: enhancement

#151 feat(frontend): improve statistics table clairity
  frontend/src/components/common/Statistic/Money.tsx
  frontend/src/components/common/Statistic/Number.tsx
  frontend/src/components/common/Statistic/Percent.tsx
  frontend/src/components/common/Statistic/StatisticContainer.ts
Labels: enhancement

#152 feat(frontend): show statistic descriptions for boardings, alightings, and trips that could use public transit
  frontend/src/components/common/Statistic/Figure.tsx
  frontend/src/components/common/Statistic/Money.tsx
  frontend/src/components/common/Statistic/Number.tsx
  frontend/src/components/common/Statistic/Percent.tsx
  frontend/src/components/common/Statistic/StatisticContainer.ts
  frontend/src/views/FutureOpportunities.tsx
  frontend/src/views/GeneralAccess.tsx
Labels: enhancement

#153 feat(frontened): improve mobile mode usability
  frontend/src/components/common/ErrorBoundary/ErrorBoundary.ts
  frontend/src/components/common/Map/Map.tsx
  frontend/src/components/common/Section/Section.tsx
  frontend/src/components/layout/CoreFrame/CoreFrame.tsx
  frontend/src/components/layout/PageHeader/PageHeader.tsx
  frontend/src/views/EssentialServicesAccess.tsx
  frontend/src/views/FutureOpportunities.tsx
  frontend/src/views/GeneralAccess.tsx
  frontend/src/views/RoadsVsTransit.tsx
Labels: bug, enhancement
