Repository shi-institute/gc-mobility-dashboard, pull requests merged in 2025-09, with the labels that each got.

#168 fix(frontend): replace current URL when new options instead of adding a new history entry
  frontend/src/components/options/areas/SelectedArea.tsx
  frontend/src/components/options/compare/useComparisonModeState.tsx
  frontend/src/components/options/futures/SelectedFutureRoutes.tsx
  frontend/src/components/options/job-access-areas/SelectedJobAccessArea.tsx
  frontend/src/components/options/seasons/SelectedSeason.tsx
  frontend/src/components/options/travel-method/SelectTravelMethod.tsx
Labels: bug

#169 fix(frontend): draw solid color behind buttons that are on top of text and other graphics
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/IconButton/IconButton.tsx
  frontend/src/components/common/Map/Map.tsx
  frontend/src/components/layout/CoreFrame/SidebarWrapper.tsx
Labels: enhancement

#172 feat(frontend): misc. tab 5 enhancements and fixes
  frontend/src/views/RoadsVsTransit.tsx
Labels: bug, enhancement

#176 feat(frontend): hide population stats figures with a sample size less than 30 people
  frontend/src/components/common/Statistic/plot/PlotContainer.tsx
  frontend/src/components/sections/AreaDemographics.tsx
  frontend/src/components/sections/RiderDemographics.tsx
  frontend/src/components/sections/WorkAndSchool2.tsx
Labels: enhancement

#177 feat(frontend): respect `prefers-reduced-motion` for transitions
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/IconButton/IconButton.tsx
  frontend/src/components/common/Map/Map.tsx
  frontend/src/components/common/Select/SelectOne.tsx
  frontend/src/components/common/TreeMap/TreeMap.tsx
  frontend/src/components/layout/CoreFrame/CoreFrame.tsx
  frontend/src/components/layout/CoreFrame/SidebarWrapper.tsx
  frontend/src/components/layout/OptionTrack/OptionButton.tsx
  frontend/src/utils/zoomToLayers.ts
  frontend/src/views/RoadsVsTransit.tsx
Labels: enhancement

#187 fix: ensure keyboard navigation and focus styles are usable throughout the app
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Map/Map.tsx
  frontend/src/components/common/NavBarItem/NavBarItem.tsx
  frontend/src/components/common/ToggleSwitch/ToggleSwitch.tsx
  frontend/src/components/layout/CoreFrame/CoreFrame.tsx
  frontend/src/components/layout/CoreFrame/SidebarWrapper.tsx
Labels: bug, enhancement

#188 fix(frontend): ensure sections+map tabs indices are the same in the tabs area and the content area
  frontend/src/components/layout/CoreFrame/CoreFrame.tsx
Labels: bug

#189 feat(frontend): wrap the commute travel method selector on tab1 in a `StatisticContainer`
  frontend/src/components/sections/WorkAndSchoolCommute.tsx
Labels: enhancement

#193 feat(frontend): add tab explainer text from Stephen
  frontend/src/assets/theme.css
  frontend/src/components/layout/PageHeader/PageHeader.tsx
  frontend/src/views/EssentialServicesAccess.tsx
  frontend/src/views/FutureOpportunities.tsx
  frontend/src/views/GeneralAccess.tsx
  frontend/src/views/JobAccess.tsx
  frontend/src/views/RoadsVsTransit.tsx
Labels: documentation, enhancement

#194 fix(frontend): do not render tab5 explainer text on tob of scenario bubbles
  frontend/src/views/RoadsVsTransit.tsx
Labels: bug

#200 fix: use non-home commute destinations for tab 3 (job access) instead of all trip destinations
  data-pipeline/src/etl/sources/future_routes/etl.py
  data-pipeline/src/etl/sources/replica/process_etl.py
  frontend/src/components/common/TreeMap/TreeMap.tsx
  frontend/src/components/layout/PageHeader/PageHeader.tsx
  frontend/src/data.d.ts
  frontend/src/views/JobAccess.tsx
Labels: bug, enhancement

#201 feat(frontend): zoom to highlighted features on tab 5 (roads or transit)
  frontend/src/utils/index.ts
  frontend/src/utils/map/highlightFeatures.ts
  frontend/src/utils/map/zoomToLayers.ts
  frontend/src/utils/requireKey.ts
  frontend/src/utils/toSqlList.ts
  frontend/src/views/RoadsVsTransit.tsx
Labels: bug, enhancement

#207 feat: add subtab to tab5 for listing all scenario features in one view
  frontend/src/data.d.ts
  frontend/src/hooks/useAppData.ts
  frontend/src/views/RoadsVsTransit.tsx
Labels: enhancement

#209 feat(frontend): clairify the time window for boardings and alightings
  frontend/src/components/sections/ServiceStatistics.tsx
Labels: enhancement

#215 fix: do not put custom map popups in shadow root
  frontend/src/assets/theme.css
  frontend/src/utils/createPopupRoot.tsx
Labels: bug

#219 feat(frontend): do not show ridership percentages and demographics when data are unavailable
  frontend/src/components/common/Statistic/plot/PlotContainer.tsx
  frontend/src/components/sections/RiderDemographics.tsx
  frontend/src/components/sections/WorkAndSchoolCommute.tsx
Labels: enhancement

#221 fix(pipeline): fix `calculate_public_transit_population_statistics` for full_area
  data-pipeline/src/etl/sources/replica/process_etl.py
Labels: bug

#222 feat(frontend): limit childcare popup attributes to facility type, capacity, and address (Google Maps link)
  frontend/src/hooks/useMapData.tsx
Labels: enhancement
